### ISSUE TITLE
tools/split-train.sh comment refers to v4, but S3 has v5 data set

### ISSUE THREAD

**Issue by tralfamadude** [shehel/BERT_progaganda_detection#2]
tools/split-train.sh comment refers to v4, but S3 has v5 data set; the directories in the unzipped v5 data do not match dirs in tools/split-train.sh

Result is the training data does not get setup correctly.

**Comment by shehel** [comment]
split-train.sh was edited to work with v2 dataset which was the final revision of NLP4IF. I think the one in S3 is an older version corresponding to [this](https://www.datasciencesociety.net/hack-news-datathon/) event.
