### ISSUE TITLE
train.py --testDataset arg needs specification

### ISSUE THREAD

**Issue by tralfamadude** [shehel/BERT_progaganda_detection#3]
The train.py --testDataset arg needs specification; it appears in the README like:
  

> --testDataset datasets-v2/tasks-2-3/dev

but there is no dev directory. It is unclear what data it is looking for. Can v2 test data be used for v5 training data? Should some of v5 data be set aside for this?

**Comment by shehel** [comment]
—testDataset is required for the custom F1 scorer defined in tools/. It should point to the same dir you used to create the dev pickle file. In the readme, I assume this is on the train split created by running the script in tools/. But my path in Readme `--testDataset datasets-v2/tasks-2-3/dev` Is incorrect. It should be the trainsplit train-dev dir. I’ll correct this, sorry about it.
