### ISSUE TITLE
Fixed Failure to Learn

### ISSUE THREAD

**Issue by depshad** [shehel/BERT_progaganda_detection#4]
Can you explain the "fixed failure to learn" commit. I've been trying Bert building my own utilities for data consumption and training loops and the model doesn't seem to learning meaningful patterns.
Help is appreciated.Thanks!!

**Comment by shehel** [comment]
This commit was due to the huggingface transformer package version. For some reason, the later versions of this package had some breaking changes that broke my code. What version of transformers are you running? The repo is based on v 1.0

**Comment by depshad** [comment]
Thanks for the reply.I'm using the version 2.4.1.The problem I see with my model is overfitting.It starts overfitting very early in 2 epochs.Can you share some pointers regarding that.I am using BertForTokenClassification model similar to this repo.

**Comment by shehel** [comment]
Try with Transformers v1.0

**Comment by depshad** [comment]
Can you please mention the value of hash_token and end_token used.

**Comment by shehel** [comment]
19 and 20
