### ISSUE TITLE
train.py missing evaluation function for classType "binary":

### ISSUE THREAD

**Issue by ziweiji** [shehel/BERT_progaganda_detection#5]
if opt.classType == "binary":
            char_predict = tools.task3_scorer_onefile.main(["-s", out_dir, "-r", opt.testDataset, "-t", opt.techniques, "-l", out_file])

Cann't find function :tools.task3_scorer_onefile.main()

**Comment by shehel** [comment]
Are you trying to do binary classification? 
Do you set this flag during train  --classType all_class ?
Binary classification was supported previously. This is not supported now since the new scorer file. 18 class classification should work.
