### ISSUE TITLE
Why nLabels is 21?

### ISSUE THREAD

**Issue by ziweiji** [shehel/BERT_progaganda_detection#6]
In your paper, you say the number of label is 20. 
"We approach the problem by classifying each token in the input article into 20 token types, i.e.,one for each of the 18 propaganda techniques, a “background” token type that signifies that the corresponding token is not part of a propaganda technique, and another “auxiliary” type to handle WordPiece tokenization."

**Comment by shehel** [comment]
Thanks for the question. 21 labels was an older appoach where the "no-propaganda" word token was separate from the "no-word" padding token. This was combined in the version that is reported in the paper. However, this change makes no difference as BERT is capable of representing this as a single token.
